name: craft_pub_dev_target_playground_three
description: A simple command-line application.
version: 1.0.3
homepage: https://www.kamilogorek.com
repository: https://www.kamilogorek.com

environment:
  sdk: '>=2.16.1 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
